.gitignore, Modules/CluedIn.Product.Toolkit/public/New-CluedInVocabularyKey.ps1, Scripts/Import-CluedInConfig.ps1
Work Item ID: AB#
Fixes various errors reported by AJG around the import of vocabulary keys.
This includes fixes for 
- Lookup vocabulary types
- More robust handling of errors
Manually tested against example data
=> feat: Handle errors correctly when updating vocabularies

.gitignore, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/allCleanProjects.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/cleanProjectDetail.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/connectorConfigurationById.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/createConnection.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/createRule.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/createStream.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/getAllConnectors.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/getAllVocabularies.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/getAllVocabularyKeys.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/getAnnotationById.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/getDataSetById.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/getDataSourceById.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/getEntityType.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/getGlossaryCategoryById.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/getGlossaryTerm.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/getGlossaryTerms.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/getInstalledConnectors.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/getRule.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/getRules.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/getStream.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/getStreams.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/getUsers.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/saveGlossaryTerm.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/saveRule.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/saveStream.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/setupConnectorStream.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/updateConfigurationSettings.gql
Work Item ID: [AB#43342](https://dev.azure.com/CluedIn-io/CluedIn/_workitems/edit/43342)
- Tested happy path of exporting everything from release 4.4.0 environment - PASSED (no errors)
- Tested happy path of importing everything to a release 4.4.0 environment - there were some errors but it will be addressed in  separate PRs to make reviewing easier
=> feat: Add / update GQL query files to support changes made during release

Modules/CluedIn.Product.Toolkit/public/Set-CluedInGlossaryTerm.ps1, Scripts/Import-CluedInConfig.ps1
Work Item ID: AB#43868
Missing parameters on update and remove version specific code
=> fix: Fix the creation and update of terms

Modules/CluedIn.Product.Toolkit/public/Set-CluedInCleanProject.ps1
Work Item ID: AB#43868
Remove unwanted properties that cause a 400 in Clean Update
=> fix: Remove unwanted properties for Updating Clean

Modules/CluedIn.Product.Toolkit/CluedIn.Product.Toolkit.psd1, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/createPreProcessDataSetRule.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/getAllPreProcessDataSetRules.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/savePreProcessDataSetRule.gql, Modules/CluedIn.Product.Toolkit/private/Invoke-CluedInGraphQL.ps1, Modules/CluedIn.Product.Toolkit/public/Get-CluedPreProcessDataSetRules.ps1, Modules/CluedIn.Product.Toolkit/public/New-CluedInPreProcessDataSetRule.ps1, Modules/CluedIn.Product.Toolkit/public/Set-CluedInPreProcessDataSetRule.ps1, Scripts/Export-CluedInConfig.ps1, Scripts/Import-CluedInConfig.ps1
Work Item ID: AB#44213
Allow PreProcessDataSetRules to be carried across environments. This also includes a fix to the paging as not all areas were being paged correctly
=> feat: Include PreProcessingRules

.gitignore, Modules/CluedIn.Product.Toolkit/CluedIn.Product.Toolkit.psd1, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/createDeduplicationMatchingRule.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/createDeduplicationProject.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/getDeduplicationMatchingRules.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/getDeduplicationProject.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/getDeduplicationProjects.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/saveDeduplicationProject.gql, Modules/CluedIn.Product.Toolkit/GraphQL/4.4.0/updateDeduplicationMatchingRule.gql, Modules/CluedIn.Product.Toolkit/private/Check-ImportResult.ps1, Modules/CluedIn.Product.Toolkit/public/Export/Export-DeduplicationProjects.ps1, Modules/CluedIn.Product.Toolkit/public/Get-CluedInDeduplicationMatchingRules.ps1, Modules/CluedIn.Product.Toolkit/public/Get-CluedInDeduplicationProject.ps1, Modules/CluedIn.Product.Toolkit/public/Get-CluedInDeduplicationProjects.ps1, Modules/CluedIn.Product.Toolkit/public/Import/Import-DeduplicationProjects.ps1, Modules/CluedIn.Product.Toolkit/public/New-CluedInCleanProject.ps1, Modules/CluedIn.Product.Toolkit/public/New-CluedInDeduplicationMatchingRule.ps1, Modules/CluedIn.Product.Toolkit/public/New-CluedInDeduplicationProject.ps1, Modules/CluedIn.Product.Toolkit/public/Set-CluedInCleanProject.ps1, Modules/CluedIn.Product.Toolkit/public/Set-CluedInDeduplicationMatchingRule.ps1, Modules/CluedIn.Product.Toolkit/public/Set-CluedInDeduplicationProject.ps1, Scripts/Export-CluedInConfig.ps1, Scripts/Import-CluedInConfig.ps1
#51)
Work Item ID: AB#44226
Allow the creation export/import of deduplication projects.
I have also started moving the code around to make it easier to maintain. I will do a seperate PR to complete this in the dev branch
Manual tests
=> feat: Allow export of deduplication projects

Modules/CluedIn.Product.Toolkit/CluedIn.Product.Toolkit.psd1, Modules/CluedIn.Product.Toolkit/public/Export/Export-DataSets.ps1, Modules/CluedIn.Product.Toolkit/public/Export/Export-DataSourceSets.ps1, Modules/CluedIn.Product.Toolkit/public/Import/Import-DataSets.ps1, Modules/CluedIn.Product.Toolkit/public/Import/Import-DataSources.ps1, Modules/CluedIn.Product.Toolkit/public/Import/Import-DeduplicationProjects.ps1, Modules/CluedIn.Product.Toolkit/public/New-CluedInAnnotation.ps1, Modules/CluedIn.Product.Toolkit/public/Set-CluedInAnnotation.ps1, Scripts/Export-CluedInConfig.ps1, Scripts/Import-CluedInConfig.ps1
Work Item ID: AB#44706
The main purpose of this is to allow the moving of the advanced mapping. Along side this I have movedthe DataSet, DataSource, DataSourceGroups and Annotations export/import into the new structure. 
=> feat: Export and Import Advanced mapping

Modules/CluedIn.Product.Toolkit/public/Import/Import-DataSets.ps1
Merge release 4.4.0 back to develop
=> fix: Update dataset preprocessing rules not working

Modules/CluedIn.Product.Toolkit/public/Import/Import-VocabularyKeys.ps1
Merge release 4.4.1 into develop
=> chore: Add extra logging information

Modules/CluedIn.Product.Toolkit/GraphQL/getDeduplicationProjects.gql, Modules/CluedIn.Product.Toolkit/public/Import/Import-VocabularyKeys.ps1
=> chore: Merge release/4.4.1 into main

Modules/CluedIn.Product.Toolkit/public/Get-CluedInRules.ps1, Modules/CluedIn.Product.Toolkit/public/Import/Import-Streams.ps1, Scripts/Import-CluedInConfig.ps1
Merge fixes back to develop from release/4.4.1
=> fix: Missing pagination when getting rules

Modules/CluedIn.Product.Toolkit/public/Import/Import-Glossaries.ps1, Modules/CluedIn.Product.Toolkit/public/Import/Import-VocabularyKeys.ps1, Pipelines/publish-powershell-module.yaml, Scripts/Import-CluedInConfig.ps1
Fixes for lookup glossary terms
=> merge release/4.4.1 back to develop

Modules/CluedIn.Product.Toolkit/public/Get-CluedInRules.ps1, Modules/CluedIn.Product.Toolkit/public/Import/Import-Glossaries.ps1, Modules/CluedIn.Product.Toolkit/public/Import/Import-Streams.ps1, Modules/CluedIn.Product.Toolkit/public/Import/Import-VocabularyKeys.ps1, Pipelines/publish-powershell-module.yaml, Scripts/Import-CluedInConfig.ps1
=> Merge 4.4.1 into main

Modules/CluedIn.Product.Toolkit/public/Import/Import-DataSets.ps1
Work Item ID: AB#45691
It took over an hour to run through the mapping part of the script when there were large amounts of mappings. This improves the performance by not doing repeated requests in foreach loops unnecessarily.
On the data set I was provided it drops the time from 01:40 to 00:18
=> feat: Improve performance of Import-DataSets

.github/workflows/release.yml
=> Merge 4.4.1 to develop

Modules/CluedIn.Product.Toolkit/CluedIn.Product.Toolkit.psd1, Modules/CluedIn.Product.Toolkit/GraphQL/saveDataBaseConfigurationForDataSource.gql, Modules/CluedIn.Product.Toolkit/public/Import/Import-DataSets.ps1, Modules/CluedIn.Product.Toolkit/public/Import/Import-DataSources.ps1, Modules/CluedIn.Product.Toolkit/public/Set-CluedInDataSourceDatabaseConfiguration.ps1
Work Item ID: AB#45969
When creating a data base type data source we were not configuring things correctly which would cause issues in the UI. We are now setting everything in the DB config apart from the password.
As such they must go and provide the password and possibly update the rest of the connection settings such as the host. We do a similar process for export targets
=> fix: Configure database fields on data sources

Modules/CluedIn.Product.Toolkit/CluedIn.Product.Toolkit.psd1, Modules/CluedIn.Product.Toolkit/GraphQL/saveDataBaseConfigurationForDataSource.gql, Modules/CluedIn.Product.Toolkit/public/Import/Import-DataSets.ps1, Modules/CluedIn.Product.Toolkit/public/Import/Import-DataSources.ps1, Modules/CluedIn.Product.Toolkit/public/Set-CluedInDataSourceDatabaseConfiguration.ps1
Merge release/4.4.1 -> develop
=> chore: Merge release/4.4.1 -> develop

Modules/CluedIn.Product.Toolkit/private/Invoke-CluedInGraphQL.ps1
Work Item ID: AB#
Pagination is not working when exporting Export Targets
=> fix: Broken pagination when exporting export targets

Modules/CluedIn.Product.Toolkit/CluedIn.Product.Toolkit.psd1, Modules/CluedIn.Product.Toolkit/GraphQL/getAllTerms.gql, Modules/CluedIn.Product.Toolkit/GraphQL/saveDataBaseConfigurationForDataSource.gql, Modules/CluedIn.Product.Toolkit/private/Invoke-CluedInGraphQL.ps1, Modules/CluedIn.Product.Toolkit/public/Get-CluedInDataSource.ps1, Modules/CluedIn.Product.Toolkit/public/Get-CluedInGlossaryTags.ps1, Modules/CluedIn.Product.Toolkit/public/Import/Import-DataSets.ps1, Modules/CluedIn.Product.Toolkit/public/Import/Import-DataSources.ps1, Modules/CluedIn.Product.Toolkit/public/Set-CluedInDataSourceDatabaseConfiguration.ps1, Modules/CluedIn.Product.Toolkit/public/Set-CluedInGlossaryTerm.ps1
=> chore: Merge release/4.4.1 into mai

Modules/CluedIn.Product.Toolkit/CluedIn.Product.Toolkit.psd1, Modules/CluedIn.Product.Toolkit/GraphQL/getAllTerms.gql, Modules/CluedIn.Product.Toolkit/GraphQL/saveDataBaseConfigurationForDataSource.gql, Modules/CluedIn.Product.Toolkit/private/Invoke-CluedInGraphQL.ps1, Modules/CluedIn.Product.Toolkit/public/Get-CluedInDataSource.ps1, Modules/CluedIn.Product.Toolkit/public/Get-CluedInGlossaryTags.ps1, Modules/CluedIn.Product.Toolkit/public/Import/Import-DataSets.ps1, Modules/CluedIn.Product.Toolkit/public/Import/Import-DataSources.ps1, Modules/CluedIn.Product.Toolkit/public/Set-CluedInDataSourceDatabaseConfiguration.ps1, Modules/CluedIn.Product.Toolkit/public/Set-CluedInGlossaryTerm.ps1
!-- PR workflow process: https://dev.azure.com/CluedIn-io/CluedIn/_wiki/wikis/CluedIn.wiki/77/Pull-Request-Process -->
Merge main back to develop
=> chore: Merge main to develop

Modules/CluedIn.Product.Toolkit/public/Import/Import-VocabularyKeys.ps1
We were not resolving the glossary term lookups for vocabulary keys when we were updating them
Fixes glossary terms not being resolved when updating a lookup vocabulary key
=> fix: Resolve glossary term lookup when updating a vocab key
